spring:
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/auth
    username: user
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false

kafka:
  url: kafka

security:
  key: b8a2d9a1-fc57-4bb3-9e39-7e56ff4c07d1