name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Download Java v17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Setting application.yml
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Build Docker Image
        run: docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/back .

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/back

  deploy:
    name: CD
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Run Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_ID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/back
            sudo docker stop back
            sudo docker container rm back
            sudo docker run -dit -p 8080:8080 --name back --network server --network monitoring_server --network db_server -v /home/ubuntu/files:/app/files ${{secrets.DOCKERHUB_USERNAME}}/back
            sudo docker image prune -f